spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/system
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always